### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by zackhsi** [ricobl/copy-ruby-member-reference#2]
👍 thanks for the extension! It's ~almost what I need.

I'd like to make a minor update to make the copied reference REPL-friendly, i.e. replace the `#` with a `.`, but I'm having trouble getting the tests to run.

The README says:

> Open the debug viewlet (Ctrl+Shift+D or Cmd+Shift+D on Mac) and from the launch configuration dropdown pick Extension Tests.

However, there is no launch.json file checked in.

When I run `npm run test` directly, I get the error described in https://github.com/microsoft/vscode/issues/93097.

Do you have any pointers?

Thanks!

**Comment by ricobl** [comment]
Hey @zackhsi! I'm sorry it took so long to reply, I might need to adjust my notification settings for this project.

I just added the `launch.json` and `tasks.json` to version control and tested on a clean checkout, let me know if that works for you.

I only run tests from vscode, I never could make it work with `npm run test`.

**Comment by ricobl** [comment]
> I'd like to make a minor update to make the copied reference REPL-friendly, i.e. replace the `#` with a `.`, but I'm having trouble getting the tests to run.

Interesting, the `#` separator is used for instance methods, so it would need an instance for using in a REPL. Can you elaborate on your use case?

**Comment by zackhsi** [comment]
Thank you! I appreciate your project, and will close this issue 👍
